export const INIT_GAME_STATE = 'INIT_GAME_STATE';
export const OPONENT_HAS_DISCONNECTED = 'OPONENT_HAS_DISCONNECTED';
export const RESET_STATE = 'RESET_STATE';
export const SELECT_ENTITY = 'SELECT_ENTITY';
export const SWITCH_ACTIVE_PLAYER = 'SWITCH_ACTIVE_PLAYER';
