export default [
  {
    id: 2,
    name: 'San Martin',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Una derrota peleada vale más que una victoria casual',
  },
  {
    id: 3,
    name: 'El Indio',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Vivir solo cuesta vida',
  },
  {
    id: 4,
    name: 'Carlos Saul Mennem',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Estamos mal, pero vamos bien',
  },
  {
    id: 5,
    name: 'Diego Maradona',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Me cortaron las piernas',
  },
  {
    id: 6,
    name: 'Carlos Gardel',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Mi Buenos Aires querido, cuando yo te vuelva a ver no habrá más pena ni olvido',
  },
  {
    id: 7,
    name: 'Lionel Messi',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'No me salió ninguno zurdo',
  },
  {
    id: 8,
    name: 'Andrés Ciro',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Un buen trago no viene mal cuando pega la vida con tanta sed',
  },
  {
    id: 9,
    name: 'Charly García',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'No existe una escuela que enseñe a vivir',
  },
  {
    id: 10,
    name: 'Juan Manuel de Rosas',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Quien gobierna podrá contar siempre con la cobardía de los argentinos',
  },
  {
    id: 11,
    name: 'Lingera',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'MÁS LOCA QUE UNA CABRA',
  },
  {
    id: 12,
    name: 'Tincho',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Sos famoso bro, como manejas tanta fama?',
  },
  {
    id: 13,
    name: 'Hincha de Boca',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'DALE BO, DALE BO',
  },
  {
    id: 14,
    name: 'Rolinga',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Espero que la vida me lleve donde sea',
  },
  {
    id: 15,
    name: 'Estudiante del interior',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Pá, me pasas plata?',
  },
  {
    id: 16,
    name: 'Militante',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'La historia es indetenible, y ya no se tapa con papel de diario',
  },
  {
    id: 17,
    name: 'Gaucho',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Ni la víbora me pica, ni quema mi frente el Sol',
  },
  {
    id: 18,
    name: 'El Pombero',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Que no te agarre de noche',
  },
  {
    id: 19,
    name: 'Un tipo laburante',
    attack: 1,
    health: 3,
    cost: 1,
    label: 'Algo malo debe tener el trabajo, o los ricos ya lo habrían acaparado',
  },
];
